### ISSUE TITLE
Objects listed as exports, but not present in namespace:

### ISSUE THREAD

**Issue by montenegrina** [variani/finemapr#10]
Hello,

I installed your software via: 

devtools::install_github("variani/finemapr")

When I loaded it I got this:

> library(finemapr)
Warning message:
replacing previous import ‘Matrix::head’ by ‘utils::head’ when loading ‘finemapr’ 

When I tried to do:
> load_all("~/R/x86_64-pc-linux-gnu-library/3.6/finemapr")

Loading finemapr
Skipping missing files: package.R, names.R, sumstats.R, abf.R, cojo.R, utils.R, read.R, datasets.R, files.R, plots.R, finemap.R, caviar.R, paintor.R, classMethods.R, classFinemaprPaintor.R, classFinemaprFinemap.R, classFinemaprCaviar.R, finemapr.R, ld.R, zzz.R
Warning messages:
1: replacing previous import ‘Matrix::head’ by ‘utils::head’ when loading ‘finemapr’ 
2: S3 methods ‘collect_results.FinemaprFinemap’, ‘collect_results.FinemaprPaintor’, ‘extract_credible_set.Finemapr’, ‘filename_annot.FinemaprPaintor’, ‘filename_config.FinemaprFinemap’, ‘filename_k.FinemaprFinemap’, ‘filename_ld.FinemaprFinemap’, ‘filename_ld.FinemaprPaintor’, ‘filename_log.FinemaprFinemap’, ‘filename_master.FinemaprFinemap’, ‘filename_master.FinemaprPaintor’, ‘filename_snp.FinemaprFinemap’, ‘filename_snp.FinemaprPaintor’, ‘filename_zscore.FinemaprFinemap’, ‘filename_zscore.FinemaprPaintor’, ‘plot.Finemapr’, ‘plot.FinemaprCaviar’, ‘plot.FinemaprFinemap’, ‘plot_config.FinemaprFinemap’, ‘plot_ncausal.FinemaprFinemap’, ‘plot_snp.Finemapr’, ‘plot_snp.FinemaprCaviar’, ‘plot_snp.FinemaprFinemap’, ‘plot_zscore.Finemapr’, ‘process_annot.FinemaprPaintor’, ‘process_ld.Finemapr’, ‘process_tab.Finemapr’, ‘run_tool.FinemaprFinemap’, ‘run_tool.FinemaprPaintor’, ‘write_f [... truncated] 
3: In setup_ns_exports(path, export_all, export_imports) :
  Objects listed as exports, but not present in namespace: cojo, collect_results, example_finemap, extract_credible_set, filename_annot, filename_config, filename_k, filename_ld, filename_log, filename_master, filename_snp, filename_zscore, finemapr, plot_config, plot_ncausal, plot_snp, plot_zscore, print.Finemapr, print.FinemaprCaviar, print.FinemaprFinemap, print.FinemaprPaintor, process_annot, process_ld, process_n, process_tab, proxysnps_ref_ld, proxysnps_ref_vcf, read_ld, read_zscore, ref_bed, ref_ld, ref_pop, run_caviar, run_finemap, run_paintor, run_tool, sumstats_bmi, write_files

And following your example here:

> file1_z <- system.file("extdata/region1.z", package = "finemapr")
> file1_ld <- system.file("extdata/region1.ld", package = "finemapr")
> 
> z1 <- read_zscore(file1_z)
Error in read_zscore(file1_z) : could not find function "read_zscore"

Can you please advise,
Thanks
Ana

**Comment by montenegrina** [comment]
Hi @variani,

can you please get back to me about this issue?

Thanks
Ana

**Comment by variani** [comment]
@montenegrina, your last example should work now.

**Comment by variani** [comment]
Unfortunately, I don't have much time to support this package from now on. I would suggest you to build your analysis around original fine-mapping tools, e.g., FINEMAP. This package is merely a wrapper around system calls.

**Comment by montenegrina** [comment]
Thank you so much for getting back to me. Can you please tell me which find mapping tools do you prefer from all that are available?

**Comment by variani** [comment]
That depends on the problem you are trying to solve. I would suggest to check the literature or talk to your collaborators/colleges. Sorry I couldn't be of more help.
