### ISSUE TITLE
Prior K parameter for FINEMAP

### ISSUE THREAD

**Issue by gaow** [variani/finemapr#3]
Hi @variani great work with the `finemapr` package!

I'm currently looking at the `run_finemap` function. I'm wondering if it is possible to add in the prior `K` parameter for `FINEMAP`, and set it to default when not specified? Thanks!

**Comment by variani** [comment]
Hi,

I should say (also see an updated readme file) this package is my experimentation of running the fine mapping tools in a systematic and less painful manner (mainly for myself). I started it for one of my projects, but it is nice to see other people find it interesting.

My initial idea was to use only `args` argument to tune the analysis pipeline, but your request requires adding some more logic and other arguments. As I am switching to `finemapr` function, I updated the code only there. Examples in demo [demo/num-causal-snps.R](https://github.com/variani/finemapr/blob/master/demo/num-causal-snps.R) seem to work. 

Let me know if it is enough for your needs.

Also, the finemap authors recently released a new version, where they changed the name of the argument for the number of causal snps (surprise!). Check http://www.christianbenner.com/.

Best,
Andrey

**Comment by gaow** [comment]
Thank you Andrey! Yes being a fellow citizen in the field I completely understood the scope of projects like this and the bandwidth one person can contribute in seriously supporting it. Nonetheless I opened this ticket precisely to send a message that this is a useful project. 

> My initial idea was to use only args argument to tune the analysis pipeline

That is a good design call. I think `k` here (for now) is the only exception. And now it is taken care of. Thank you!

> Also, the finemap authors recently released a new version

Thanks a lot for this pointer! This is exactly the type of conversation I was hoping to initialize with a ticket like this :) 

Best,
Gao

**Comment by variani** [comment]
Definitely, feel free to create issues or pull requests!

Glad to see that your particular issue about `k` is resolved. So, I close this ticket.
