### ISSUE TITLE
Question about tutorial

### ISSUE THREAD

**Issue by montenegrina** [variani/finemapr#9]
Hello,

Can you please tell me what is:
n1 <- 5363
is that number of cases+controls?
in:
https://variani.github.io/finemapr/vignettes/finemapr.html

Also would you recommend running this per individual GWAS (I have 3 GWASes) or for META ?

Thanks
Ana

**Comment by variani** [comment]
HI Ana,

In GWAS summary statistics of binary traits, the effective sample size is computed as in Eq 3 [here](https://www.nature.com/articles/s41467-020-14594-5).

The common practice is to run fine-mapping on meta-analyzed GWAS results. If cohorts are of different ancestry, you might want to consider other options.

Best,
Andrey

**Comment by montenegrina** [comment]
Thanks. So just the confirm n1 from your example is actually the Effective Sample Size calculated just like in the equation in attach, where Ncases would be the sum of all cases for all of my 3 cohorts I assume.

**Comment by variani** [comment]
Indeed, this example with `n1` is copied from the FINEMAP website, as references in the vignette. So I cannot give your more details. I believe that `n1` would be the actual sample size, if the trait was quantitative, and the effective sample size, if trait was binary. 

I think that your question is out of the scope of `finemapr`, as the user is responsible to prepare appropriate input data to run any fine mapping tool. I would recommend to check the documentation of fine-mapping tool of your choice and clarify the format.
